### ISSUE TITLE
Hi, I tried your example but I'm getting: Unknown field 'objectValue' on type 'LettersJson!'

### ISSUE THREAD

**Issue by tomitrescak** [diegonc/gatsby-transformer-rawjson#1]
Whatever I specify in my query it always complains that it wants a selection of subfields

**Comment by diegonc** [comment]
Hello, I just added an example where the query works, so you can compare with what you are doing.

```GraphQL
query MyQuery {
  allDataJson {
    nodes {
      childRawDataJson {
        objectValue
      }
    }
  }
}
```

The example is just a blank project (`gatsby new example`) where `gatsby-transformer-json` and `gatsby-transformer-rawjson` was added and configured.

However, for some reason gatsby wants the plugin installed from npm repository. Relative paths did not work.

**Comment by diegonc** [comment]
Please, reopen if things still do not work after looking at the example. Thanks
